exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("photo")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("photo").insert([
        {
          id: 1,
          photo_url: "https://i.imgur.com/mgDTGqs.jpg",
          photo_name: "Trang An port",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 2,
          photo_url: "https://i.imgur.com/gCje17E.jpg",
          photo_name: "Sao Khe river",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 3,
          photo_url: "https://i.imgur.com/fuVYrKo.jpg",
          photo_name: "Flowing with Sao Khe river",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 4,
          photo_url: "https://i.imgur.com/AHRpqHX.jpg",
          photo_name: "Flowing with Sao Khe river",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 5,
          photo_url: "https://i.imgur.com/CydMwTb.jpg",
          photo_name: "Entering the tunnel",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 6,
          photo_url: "https://i.imgur.com/hkXWZlX.jpg",
          photo_name: "Under the tunnel",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 7,
          photo_url: "https://i.imgur.com/tzSpocD.jpg",
          photo_name: "Hang Hac bird",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 8,
          photo_url: "https://i.imgur.com/LErff40.jpg",
          photo_name: "Hang Hac bird",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 9,
          photo_url: "https://i.imgur.com/xX6NyY1.jpg",
          photo_name: "Exit the tunnel",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 10,
          photo_url: "https://i.imgur.com/C7opzb6.jpg",
          photo_name: "Tourist",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 11,
          photo_url: "https://i.imgur.com/5ZWKSJJ.jpg",
          photo_name: "The boat lady",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 12,
          photo_url: "https://i.imgur.com/1KdNJkV.jpg",
          photo_name: "The boat lady",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 13,
          photo_url: "https://i.imgur.com/WBWuT8d.jpg",
          photo_name: "Goat",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 14,
          photo_url: "https://i.imgur.com/2szbpqn.jpg",
          photo_name: "Mistery bird",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 15,
          photo_url: "https://i.imgur.com/E51D9ZC.jpg",
          photo_name: "A riverside temple",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 16,
          photo_url: "https://i.imgur.com/EuMBInz.jpg",
          photo_name: "His lunch",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 17,
          photo_url: "https://i.imgur.com/POaDqnz.jpg",
          photo_name: "Another mistery bird",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 18,
          photo_url: "https://i.imgur.com/9EDCq5M.jpg",
          photo_name: "Hanging out with friends",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 19,
          photo_url: "https://i.imgur.com/pKsFE9Y.jpg",
          photo_name: "Hunting time",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 20,
          photo_url: "https://i.imgur.com/SWstlKm.jpg",
          photo_name: "Top of mountain temple",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 21,
          photo_url: "https://i.imgur.com/Z52Gi0m.jpg",
          photo_name: "Local Trang An people",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 22,
          photo_url: "https://i.imgur.com/qzJxzEC.jpg",
          photo_name: "Tour de Trang An",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 23,
          photo_url: "https://i.imgur.com/TC8ruTK.jpg",
          photo_name: "Floating groceries store",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 24,
          photo_url: "https://i.imgur.com/74FMu1h.jpg",
          photo_name: "Water Lilly",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 25,
          photo_url: "https://i.imgur.com/Fsjn4Yt.jpg",
          photo_name: "Flowing with the tour",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 26,
          photo_url: "https://i.imgur.com/Ek5vRTT.jpg",
          photo_name: "Water Lilly",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 27,
          photo_url: "https://i.imgur.com/FClZy5g.jpg",
          photo_name: "Tam Quan Gate",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        },
        {
          id: 28,
          photo_url: "https://i.imgur.com/NAcB9uV.jpg",
          photo_name: "Tam Quan Gate",
          short_description: "",
          long_description: "",
          place_taken: "Ninh Binh, Vietnam",
        }
      ]);
    });
};

